feat: add new shadowsocks-v2ray-tls servers
WeAreMahsaAmini/FreeInternet pull request #24
Opened 2022-10-05 10:55 UTC by masoudkazemi

Adding 2 new servers. I will create a new separate PR for suggesting [Shadowlink iOS app](https://apps.apple.com/us/app/shadowlink-shadowsocks-vpn/id1439686518) which I've tested and it works fine with the same ss URL.

2022-10-05 11:12 UTC, Pr0nE commented
Thanks,
I've tested this app but didn't work for me(VPN connects, but can't do anything)
It has Shadowsocks config but doesn't support plugins to add v2ray, how did you manage to add plugin?

2022-10-05 11:57 UTC, masoudkazemi commented
Sorry, my mistake, as you mentioned it doesn't support the plugin. Never mind.

2022-10-07 22:11 UTC, 0xland requested changes

2022-10-07 22:11 UTC, 0xland commented on guides/shadowsocks-v2ray-tls/CONFIGS.md
> +ss://YWVzLTI1Ni1nY206OTVDRTdCNzQtQ0Y4Ni00NUQyLUE0NEUtQzAzOUE1QkQxMjY4@tmug.ir:443?plugin=v2ray-plugin%3Bpath%3D%2Frabbitmq%3Bloglevel%3Dnone%3Bhost%3Dtmug.ir%3Btls
Unfortunately These links will not work on IOS. 
IOS formats are different:
this is your IOS link:
`ss://YWVzLTI1Ni1nY206OTVDRTdCNzQtQ0Y4Ni00NUQyLUE0NEUtQzAzOUE1QkQxMjY4QHRtdWcuaXI6NDQz?tfo=1&v2ray-plugin=eyJwYXRoIjoiXC9yYWJiaXRtcSIsIm11eCI6dHJ1ZSwidGZvIjp0cnVlLCJob3N0IjoidG11Zy5pciIsIm1vZGUiOiJ3ZWJzb2NrZXQiLCJ0bHMiOnRydWV9`

2022-10-07 22:11 UTC, 0xland commented on guides/shadowsocks-v2ray-tls/CONFIGS.md
> +ss://YWVzLTI1Ni1nY206OTVDRTdCNzQtQ0Y4Ni00NUQyLUE0NEUtQzAzOUE1QkQxMjY4@golechai.ir:443?plugin=v2ray-plugin%3Bpath%3D%2Frabbitmq%3Bloglevel%3Dnone%3Bhost%3Dgolechai.ir%3Btls
`ss://YWVzLTI1Ni1nY206OTVDRTdCNzQtQ0Y4Ni00NUQyLUE0NEUtQzAzOUE1QkQxMjY4QGdvbGVjaGFpLmlyOjQ0Mw?tfo=1&v2ray-plugin=eyJwYXRoIjoiXC9yYWJiaXRtcSIsIm11eCI6dHJ1ZSwidGZvIjp0cnVlLCJob3N0IjoiZ29sZWNoYWkuaXIiLCJtb2RlIjoid2Vic29ja2V0IiwidGxzIjp0cnVlfQ`

2022-10-07 23:22 UTC, masoudkazemi commented on guides/shadowsocks-v2ray-tls/CONFIGS.md
> +ss://YWVzLTI1Ni1nY206OTVDRTdCNzQtQ0Y4Ni00NUQyLUE0NEUtQzAzOUE1QkQxMjY4@tmug.ir:443?plugin=v2ray-plugin%3Bpath%3D%2Frabbitmq%3Bloglevel%3Dnone%3Bhost%3Dtmug.ir%3Btls
Added, thanks.

2022-10-08 14:30 UTC, merged