add some screen shots for android
WeAreMahsaAmini/FreeInternet pull request #4
Opened 2022-10-01 09:31 UTC by payam-zahedi

2022-10-02 01:50 UTC, farnoodma requested changes
Thank you for your PR, however, some small things need to be changed before getting merged.

2022-10-02 01:50 UTC, farnoodma commented on README.md
> +- the tap on the  "Import From Clipboard" item.
Did you mean "Then tap the .."?

2022-10-02 01:50 UTC, farnoodma commented on README.md
> +- tab plus button from upper right corner and tab.
"Tap the plus button from the upper right corner" is correct.

2022-10-02 01:50 UTC, farnoodma commented on README.md
>  - Select the newly added server from the list and tab paper plane button.
Not one of your changes, but I think it would be great if you change this too: "... and tap the paper plane button."

2022-10-07 15:30 UTC, payam-zahedi commented
Thanks, @farnoodma.
I updated the PR and fixed issues

2022-10-07 22:23 UTC, merged